# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.4'

networks:
  supply-chain-network:
    external: "true"
    name: supply-chain-network

services:

  ca_oem:
    image: hyperledger/fabric-ca:1.4.9
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-oem
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/oem:/etc/hyperledger/fabric-ca-server
    container_name: ca_oem
    networks:
      - supply-chain-network

  ca_oem_orderer:
    image: hyperledger/fabric-ca:1.4.9
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-oem-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/oemorderer:/etc/hyperledger/fabric-ca-server
    container_name: ca_oem_orderer
    networks:
      - supply-chain-network
