# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.4'
volumes:
  orderer.oem.scm.com:
  peer0.oem.scm.com:
networks:
  supply-chain-network:
    external: "true"
    name: supply-chain-network
services:
  orderer.oem.scm.com:
    container_name: orderer.oem.scm.com
    image: hyperledger/fabric-orderer:2.3.1
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OEMOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/oem.scm.com/orderers/orderer.oem.scm.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/oem.scm.com/orderers/orderer.oem.scm.com/tls/:/var/hyperledger/orderer/tls
      - orderer.oem.scm.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
    networks:
      - supply-chain-network
  peer0.oem.scm.com:
    container_name: peer0.oem.scm.com
    image: hyperledger/fabric-peer:2.3.1
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=supply-chain-network
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.oem.scm.com
      - CORE_PEER_ADDRESS=peer0.oem.scm.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.oem.scm.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.oem.scm.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.oem.scm.com:7051
      - CORE_PEER_LOCALMSPID=OEMMSP
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/oem.scm.com/peers/peer0.oem.scm.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/oem.scm.com/peers/peer0.oem.scm.com/tls:/etc/hyperledger/fabric/tls
      - peer0.oem.scm.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - supply-chain-network
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.3.1
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG

      - CORE_PEER_LOCALMSPID=OEMMSP
      - CORE_PEER_TLS_ROOTCERT_FILE=organizations/peerOrganizations/oem.scm.com/peers/peer0.oem.scm.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=organizations/peerOrganizations/oem.scm.com/users/Admin@oem.scm.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=organizations/peerOrganizations/oem.scm.com/peers/peer0.oem.scm.com/tls/server.crt
      - orgAddress=oem.scm.com
      - peer_LISTENPORT=7051
      - orderer_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../config/:/etc/hyperledger/fabric/config/
      - ../files/scripts/dockerCommitCC.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/dockerCommitCC.sh
    depends_on:
      - peer0.oem.scm.com
    networks:
      - supply-chain-network
