# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.4'
volumes:
  orderer.<orgAddress>:
  peer0.<orgAddress>:
networks:
  <NETWORK_NAME>:
    external: "true"
    name: <NETWORK_NAME>
services:
  orderer.<orgAddress>:
    container_name: orderer.<orgAddress>
    image: hyperledger/fabric-orderer:<FABRIC_VER>
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=<orderer_LISTENPORT>
      - ORDERER_GENERAL_LOCALMSPID=<ORG>OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:<orderer_Admin_ListenPort>
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/<orgAddress>/orderers/orderer.<orgAddress>/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/<orgAddress>/orderers/orderer.<orgAddress>/tls/:/var/hyperledger/orderer/tls
      - orderer.<orgAddress>:/var/hyperledger/production/orderer
    ports:
      - <orderer_LISTENPORT>:<orderer_LISTENPORT>
      - <orderer_Admin_ListenPort>:<orderer_Admin_ListenPort>
    networks:
      - <NETWORK_NAME>
  peer0.<orgAddress>:
    container_name: peer0.<orgAddress>
    image: hyperledger/fabric-peer:<FABRIC_VER>
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=<NETWORK_NAME>
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.<orgAddress>
      - CORE_PEER_ADDRESS=peer0.<orgAddress>:<peer_LISTENPORT>
      - CORE_PEER_LISTENADDRESS=0.0.0.0:<peer_LISTENPORT>
      - CORE_PEER_CHAINCODEADDRESS=peer0.<orgAddress>:<peer_CC_Port>
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:<peer_CC_Port>
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.<orgAddress>:<peer_LISTENPORT>
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.<orgAddress>:<peer_LISTENPORT>
      - CORE_PEER_LOCALMSPID=<ORG>MSP
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../organizations/peerOrganizations/<orgAddress>/peers/peer0.<orgAddress>/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/<orgAddress>/peers/peer0.<orgAddress>/tls:/etc/hyperledger/fabric/tls
      - peer0.<orgAddress>:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - <peer_LISTENPORT>:<peer_LISTENPORT>
    networks:
      - <NETWORK_NAME>
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:<FABRIC_VER>
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG

      - CORE_PEER_LOCALMSPID=<ORG>MSP
      - CORE_PEER_TLS_ROOTCERT_FILE=organizations/peerOrganizations/<orgAddress>/peers/peer0.<orgAddress>/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=organizations/peerOrganizations/<orgAddress>/users/Admin@<orgAddress>/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=organizations/peerOrganizations/<orgAddress>/peers/peer0.<orgAddress>/tls/server.crt
      - orgAddress=<orgAddress>
      - peer_LISTENPORT=<peer_LISTENPORT>
      - orderer_LISTENPORT=<orderer_LISTENPORT>
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../config/:/etc/hyperledger/fabric/config/
      - ../files/scripts/dockerCommitCC.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/dockerCommitCC.sh
    depends_on:
      - peer0.<orgAddress>
    networks:
      - <NETWORK_NAME>
